name: Adobe Sign Alert
on:
  repository_dispatch:
    types: [adobe_doc_signed] # Must match $EventType in your PowerShell

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          # ACCESS THE PAYLOAD HERE:
          subject: "Signed: ${{ github.event.client_payload.doc_name }}"
          to: ${{ secrets.DESTINATION_EMAIL }}
          from: "Adobe Automation <${{ secrets.MAIL_USERNAME }}>"
          body: |
            The following document was signed: ${{ github.event.client_payload.doc_name }}
            Processed at: ${{ github.event.client_payload.timestamp }}
